### ISSUE TITLE
error saat run main.py

### ISSUE THREAD

**Issue by irfanandratama** [pebbie/pebahasa#4]
mas untuk runnya dari main.py kan? saat run main.py di bottle.py ada error seperti ini:
```
Traceback (most recent call last):
  File "C:\Users\Irfan Hanandra\Documents\PythonPractice\pebahasa-master\main.py", line 2, in <module>
    from bottle import *
  File "C:\Users\Irfan Hanandra\Documents\PythonPractice\pebahasa-master\bottle.py", line 317
    except KeyError, e:
                   ^
SyntaxError: invalid syntax
```

**Comment by pebbie** [comment]
ini runtime environment-nya pakai python 3 kah? kode pebahasa semasa ditulisnya (2010) pakai python 2.x, kalau mau dijalankan di python 3.x mungkin perlu di adaptasi dulu (coba pakai 2to3).

**Comment by rendyaulia** [comment]
Mas. Untuk menjalankan nya gimana ya mas ?? Setelah menjalankan Main.py saya diarahkan ke link, apa harus kesana??
